SET foreign_key_checks = 0;
UPDATE moneda SET `simbolo` = '$', `nombre` = 'Pesos argentinos', `cotizacion` = '1', `id_remoto` = '31' WHERE `id_remoto` = '31';
UPDATE moneda SET `simbolo` = 'USD', `nombre` = 'Dólar estadounidense', `cotizacion` = '886', `id_remoto` = '32' WHERE `id_remoto` = '32';
UPDATE agrupacion SET `numero` = '1', `nombre` = 'GENERAL', `color` = '#0098DA', `icono` = 'fas fa-boxes', `id_remoto` = '24' WHERE `id_remoto` = '24';
UPDATE categoria SET `nombre` = 'CATEGORIA', `se_imprime` = '1', `id_remoto` = '22' WHERE `id_remoto` = '22';
UPDATE puntos_venta SET `numero` = '6', `descripcion` = 'Grupo SEIC', `id_remoto` = '11' WHERE `id_remoto` = '11';
UPDATE sucursales SET `nombre` = 'Grupo SEIC', `direccion` = '23 N° 1434', `telefono` = '111', `email` = 'sebastian@nexofiscal.com.ar', `contacto_nombre` = NULL, `contacto_telefono` = NULL, `contacto_email` = NULL, `referente_nombre` = NULL, `referente_telefono` = NULL, `referente_email` = NULL, `id_remoto` = '25' WHERE `id_remoto` = '25';
UPDATE roles SET `nombre` = 'cajero', `descripcion` = 'Cajero/Vendedor', `id_remoto` = '44' WHERE `id_remoto` = '44';
UPDATE roles SET `nombre` = 'admin', `descripcion` = 'Administrador', `id_remoto` = '45' WHERE `id_remoto` = '45';
UPDATE usuarios SET `nombre_usuario` = 'sebastian@nexofiscal.com.ar', `password` = 'a4431d8b0b8ed55938a2bc6ecdb7b274', `nombre_completo` = 'Administrador', `activo` = '1', `venta_rapida` = '0', `lista_precios` = '1', `imprimir` = '1', `tipo_comprobante_imprimir` = '2', `id_remoto` = '47' WHERE `id_remoto` = '47';
UPDATE tipo_documento SET `nombre` = 'DNI', `id_remoto` = '21' WHERE `id_remoto` = '21';
UPDATE tipo_documento SET `nombre` = 'L.E.', `id_remoto` = '22' WHERE `id_remoto` = '22';
UPDATE tipo_documento SET `nombre` = 'PASAPORTE', `id_remoto` = '23' WHERE `id_remoto` = '23';
UPDATE tipo_iva SET `nombre` = 'INSCRIPTO', `descripcion` = NULL, `porcentaje` = NULL, `letra_factura` = 'A', `id_remoto` = '21' WHERE `id_remoto` = '21';
UPDATE tipo_iva SET `nombre` = 'MONOTRIBUTO', `descripcion` = NULL, `porcentaje` = NULL, `letra_factura` = 'C', `id_remoto` = '22' WHERE `id_remoto` = '22';
UPDATE tipo_iva SET `nombre` = 'CONSUMIDOR FINAL', `descripcion` = NULL, `porcentaje` = NULL, `letra_factura` = 'B', `id_remoto` = '23' WHERE `id_remoto` = '23';
UPDATE tipo_iva SET `nombre` = 'RESPONSABLE EXENTO', `descripcion` = NULL, `porcentaje` = NULL, `letra_factura` = 'B', `id_remoto` = '37' WHERE `id_remoto` = '37';
UPDATE vendedores SET `nombre` = 'VENDEROR', `direccion` = NULL, `telefono` = NULL, `porcentaje_comision` = '0', `id_remoto` = '40' WHERE `id_remoto` = '40';
UPDATE codigos_barras SET `inicio` = '2', `id_long` = '5', `payload_type` = 'P', `payload_int` = '5', `long` = '13', `id_remoto` = '14' WHERE `id_remoto` = '14';
UPDATE tasa_iva SET `nombre` = 'IVA 21%', `tasa` = '0.21', `id_remoto` = '43' WHERE `id_remoto` = '43';
UPDATE tasa_iva SET `nombre` = 'IVA 10.5%', `tasa` = '0.105', `id_remoto` = '44' WHERE `id_remoto` = '44';
UPDATE tasa_iva SET `nombre` = 'Sin IVA', `tasa` = '0', `id_remoto` = '45' WHERE `id_remoto` = '45';
UPDATE familias SET `numero` = '1', `nombre` = 'GENERAL', `id_remoto` = '33' WHERE `id_remoto` = '33';
UPDATE proveedores SET `razon_social` = 'Proveedor por defecto', `direccion` = 'Calle Ejemplo 123', `telefono` = '123456789', `email` = 'proveedor@example.com', `cuit` = '11111111', `saldo_actual` = '0', `id_remoto` = '41' WHERE `id_remoto` = '41';
UPDATE tipo SET `numero` = '1', `nombre` = 'Producto', `id_remoto` = '50' WHERE `id_remoto` = '50';
UPDATE tipo SET `numero` = '2', `nombre` = 'Servicio', `id_remoto` = '51' WHERE `id_remoto` = '51';
UPDATE tipo SET `numero` = '3', `nombre` = 'Producto y servicio', `id_remoto` = '52' WHERE `id_remoto` = '52';
UPDATE unidad SET `nombre` = 'Kilogramo', `simbolo` = 'KG', `id_remoto` = '102' WHERE `id_remoto` = '102';
UPDATE unidad SET `nombre` = 'Unidad', `simbolo` = 'UN.', `id_remoto` = '103' WHERE `id_remoto` = '103';
UPDATE unidad SET `nombre` = 'Metro', `simbolo` = 'M', `id_remoto` = '104' WHERE `id_remoto` = '104';
UPDATE unidad SET `nombre` = 'Metro Cuadrado', `simbolo` = 'M2', `id_remoto` = '105' WHERE `id_remoto` = '105';
UPDATE unidad SET `nombre` = 'Metro Cubico', `simbolo` = 'M3', `id_remoto` = '106' WHERE `id_remoto` = '106';
UPDATE unidad SET `nombre` = 'Litro', `simbolo` = 'LTS.', `id_remoto` = '107' WHERE `id_remoto` = '107';
UPDATE unidad SET `nombre` = 'Gramo', `simbolo` = 'GR.', `id_remoto` = '108' WHERE `id_remoto` = '108';
UPDATE forma_pago SET `nombre` = 'EFECTIVO', `porcentaje` = '0', `activo` = '1', `id_remoto` = '27' WHERE `id_remoto` = '27';
UPDATE forma_pago SET `nombre` = 'MERCADOPAGO', `porcentaje` = '0', `activo` = '1', `id_remoto` = '29' WHERE `id_remoto` = '29';
UPDATE forma_pago SET `nombre` = 'TRANSFERENCIA', `porcentaje` = '0', `activo` = '1', `id_remoto` = '30' WHERE `id_remoto` = '30';
UPDATE forma_pago SET `nombre` = 'CUENTA CORRIENTE', `porcentaje` = '0', `activo` = '1', `id_remoto` = '35' WHERE `id_remoto` = '35';
UPDATE funciones SET `nombre` = 'comprobantes', `descripcion` = 'Comprobantes', `id_remoto` = '763' WHERE `id_remoto` = '763';
UPDATE funciones SET `nombre` = 'productos', `descripcion` = 'Productos', `id_remoto` = '764' WHERE `id_remoto` = '764';
UPDATE funciones SET `nombre` = 'clientes', `descripcion` = 'Clientes', `id_remoto` = '765' WHERE `id_remoto` = '765';
UPDATE funciones SET `nombre` = 'agrupaciones', `descripcion` = 'Agrupaciones', `id_remoto` = '766' WHERE `id_remoto` = '766';
UPDATE funciones SET `nombre` = 'categorias', `descripcion` = 'Categorias', `id_remoto` = '767' WHERE `id_remoto` = '767';
UPDATE funciones SET `nombre` = 'categoria_iibb', `descripcion` = 'Categoria IIBB', `id_remoto` = '768' WHERE `id_remoto` = '768';
UPDATE funciones SET `nombre` = 'cierre_cajas', `descripcion` = 'Cierres Cajas', `id_remoto` = '769' WHERE `id_remoto` = '769';
UPDATE funciones SET `nombre` = 'condiciones_venta', `descripcion` = 'Condiciones Venta', `id_remoto` = '770' WHERE `id_remoto` = '770';
UPDATE funciones SET `nombre` = 'configuraciones', `descripcion` = 'Configuraciones', `id_remoto` = '771' WHERE `id_remoto` = '771';
UPDATE funciones SET `nombre` = 'familias', `descripcion` = 'Familias', `id_remoto` = '772' WHERE `id_remoto` = '772';
UPDATE funciones SET `nombre` = 'formas_pago', `descripcion` = 'Formas de pago', `id_remoto` = '773' WHERE `id_remoto` = '773';
UPDATE funciones SET `nombre` = 'ganancias_clientes', `descripcion` = 'Ganancias de clientes', `id_remoto` = '774' WHERE `id_remoto` = '774';
UPDATE funciones SET `nombre` = 'ganancias_prooveedor', `descripcion` = 'Ganancias prooveedor', `id_remoto` = '775' WHERE `id_remoto` = '775';
UPDATE funciones SET `nombre` = 'listas_pecios', `descripcion` = 'Listas de pecios', `id_remoto` = '776' WHERE `id_remoto` = '776';
UPDATE funciones SET `nombre` = 'localidades', `descripcion` = 'Localidades', `id_remoto` = '777' WHERE `id_remoto` = '777';
UPDATE funciones SET `nombre` = 'marcas', `descripcion` = 'Marcas', `id_remoto` = '778' WHERE `id_remoto` = '778';
UPDATE funciones SET `nombre` = 'monedas', `descripcion` = 'Monedas', `id_remoto` = '779' WHERE `id_remoto` = '779';
UPDATE funciones SET `nombre` = 'operacion_negocio', `descripcion` = 'Operacion Negocio', `id_remoto` = '780' WHERE `id_remoto` = '780';
UPDATE funciones SET `nombre` = 'pais', `descripcion` = 'Pais', `id_remoto` = '781' WHERE `id_remoto` = '781';
UPDATE funciones SET `nombre` = 'presupuestos', `descripcion` = 'presupuestos', `id_remoto` = '782' WHERE `id_remoto` = '782';
UPDATE funciones SET `nombre` = 'productos_stock', `descripcion` = 'Productos Stock', `id_remoto` = '783' WHERE `id_remoto` = '783';
UPDATE funciones SET `nombre` = 'promociones', `descripcion` = 'Promociones', `id_remoto` = '784' WHERE `id_remoto` = '784';
UPDATE funciones SET `nombre` = 'proveedores', `descripcion` = 'proveedores', `id_remoto` = '785' WHERE `id_remoto` = '785';
UPDATE funciones SET `nombre` = 'proveedores', `descripcion` = 'Proveedores', `id_remoto` = '786' WHERE `id_remoto` = '786';
UPDATE funciones SET `nombre` = 'provincia_categoria_iibb', `descripcion` = 'Provincia Categoria IIBB', `id_remoto` = '787' WHERE `id_remoto` = '787';
UPDATE funciones SET `nombre` = 'provincia_iva_proveedor', `descripcion` = 'Provincia IVA proveedor', `id_remoto` = '788' WHERE `id_remoto` = '788';
UPDATE funciones SET `nombre` = 'provincias', `descripcion` = 'provincias', `id_remoto` = '789' WHERE `id_remoto` = '789';
UPDATE funciones SET `nombre` = 'remitos', `descripcion` = 'remitos', `id_remoto` = '790' WHERE `id_remoto` = '790';
UPDATE funciones SET `nombre` = 'roles', `descripcion` = 'Roles', `id_remoto` = '791' WHERE `id_remoto` = '791';
UPDATE funciones SET `nombre` = 'subcategoria', `descripcion` = 'Sub Categoria', `id_remoto` = '792' WHERE `id_remoto` = '792';
UPDATE funciones SET `nombre` = 'subfamilias', `descripcion` = 'Sub Familias', `id_remoto` = '793' WHERE `id_remoto` = '793';
UPDATE funciones SET `nombre` = 'sucursales', `descripcion` = 'Sucursales', `id_remoto` = '794' WHERE `id_remoto` = '794';
UPDATE funciones SET `nombre` = 'tipo', `descripcion` = 'Tipo', `id_remoto` = '795' WHERE `id_remoto` = '795';
UPDATE funciones SET `nombre` = 'tipo_comprobante', `descripcion` = 'Tipo Comprobante', `id_remoto` = '796' WHERE `id_remoto` = '796';
UPDATE funciones SET `nombre` = 'tipo_documento', `descripcion` = 'Tipo Documento', `id_remoto` = '797' WHERE `id_remoto` = '797';
UPDATE funciones SET `nombre` = 'tipo_iva', `descripcion` = 'Tipo de IVA', `id_remoto` = '798' WHERE `id_remoto` = '798';
UPDATE funciones SET `nombre` = 'tipos_cajas', `descripcion` = 'Tipos Cajas', `id_remoto` = '799' WHERE `id_remoto` = '799';
UPDATE funciones SET `nombre` = 'ubicacion', `descripcion` = 'Ubicacion', `id_remoto` = '800' WHERE `id_remoto` = '800';
UPDATE funciones SET `nombre` = 'unidad', `descripcion` = 'Unidad', `id_remoto` = '801' WHERE `id_remoto` = '801';
UPDATE funciones SET `nombre` = 'usuarios', `descripcion` = 'Usuarios', `id_remoto` = '802' WHERE `id_remoto` = '802';
UPDATE funciones SET `nombre` = 'vendedores', `descripcion` = 'Vendedores', `id_remoto` = '803' WHERE `id_remoto` = '803';
UPDATE funciones SET `nombre` = 'stock', `descripcion` = 'Stock', `id_remoto` = '804' WHERE `id_remoto` = '804';
UPDATE funciones SET `nombre` = 'gastos', `descripcion` = 'Gastos', `id_remoto` = '805' WHERE `id_remoto` = '805';
UPDATE funciones SET `nombre` = 'compras', `descripcion` = 'Compras', `id_remoto` = '806' WHERE `id_remoto` = '806';
SET foreign_key_checks = 1;
