SET foreign_key_checks = 0;
UPDATE moneda SET `simbolo` = 'USD', `nombre` = 'Dólar estadounidense', `cotizacion` = '1042', `id_remoto` = '7' WHERE `id_remoto` = '7';
UPDATE moneda SET `simbolo` = '$', `nombre` = 'Pesos Argentinos', `cotizacion` = '1', `id_remoto` = '8' WHERE `id_remoto` = '8';
UPDATE agrupacion SET `numero` = '1', `nombre` = 'CARNICERIA', `color` = '#0098DA', `icono` = 'fas fa-boxes', `id_remoto` = '10' WHERE `id_remoto` = '10';
UPDATE agrupacion SET `numero` = NULL, `nombre` = 'OTROS', `color` = '#8b9ced', `icono` = 'fas fa-boxes', `id_remoto` = '20' WHERE `id_remoto` = '20';
UPDATE categoria SET `nombre` = 'CATEGORIA', `se_imprime` = '1', `id_remoto` = '18' WHERE `id_remoto` = '18';
UPDATE puntos_venta SET `numero` = '1', `descripcion` = 'Punto de venta 1', `id_remoto` = '2' WHERE `id_remoto` = '2';
UPDATE puntos_venta SET `numero` = '2', `descripcion` = 'Punto de venta 2', `id_remoto` = '3' WHERE `id_remoto` = '3';
UPDATE puntos_venta SET `numero` = '3', `descripcion` = 'Punto de venta 3', `id_remoto` = '4' WHERE `id_remoto` = '4';
UPDATE puntos_venta SET `numero` = '99', `descripcion` = 'Punto de venta 99', `id_remoto` = '5' WHERE `id_remoto` = '5';
UPDATE sucursales SET `nombre` = 'Sucursal 1', `direccion` = ' 955, Av.123, B1900 Tolosa, Provincia de Buenos Aires', `telefono` = '2214865781', `email` = 'sucursal7@carnesleo.com.ar', `contacto_nombre` = NULL, `contacto_telefono` = NULL, `contacto_email` = NULL, `referente_nombre` = NULL, `referente_telefono` = NULL, `referente_email` = NULL, `id_remoto` = '1' WHERE `id_remoto` = '1';
UPDATE sucursales SET `nombre` = 'Sucursal 2', `direccion` = ' 333, Av. 51, B1900 La Paata, Provincia de Buenos Aires', `telefono` = '02214572612', `email` = NULL, `contacto_nombre` = NULL, `contacto_telefono` = NULL, `contacto_email` = NULL, `referente_nombre` = NULL, `referente_telefono` = NULL, `referente_email` = NULL, `id_remoto` = '2' WHERE `id_remoto` = '2';
UPDATE sucursales SET `nombre` = 'Sucursal 333', `direccion` = '608 Nº 478', `telefono` = '111111', `email` = 'nicobernasconi@gmail.com', `contacto_nombre` = NULL, `contacto_telefono` = NULL, `contacto_email` = NULL, `referente_nombre` = NULL, `referente_telefono` = NULL, `referente_email` = NULL, `id_remoto` = '19' WHERE `id_remoto` = '19';
UPDATE roles SET `nombre` = 'admin', `descripcion` = 'Administrador', `id_remoto` = '5' WHERE `id_remoto` = '5';
UPDATE roles SET `nombre` = 'vendedor', `descripcion` = 'Vendedor', `id_remoto` = '6' WHERE `id_remoto` = '6';
UPDATE roles SET `nombre` = 'responsable_caja', `descripcion` = 'Responsable de Caja', `id_remoto` = '7' WHERE `id_remoto` = '7';
UPDATE roles SET `nombre` = 'Compras', `descripcion` = 'Responsable de Compras', `id_remoto` = '8' WHERE `id_remoto` = '8';
UPDATE usuarios SET `nombre_usuario` = 'admin@carniceria.com.ar', `password` = 'e10adc3949ba59abbe56e057f20f883e', `nombre_completo` = 'Administrador', `activo` = '1', `venta_rapida` = '1', `lista_precios` = '1', `imprimir` = '1', `tipo_comprobante_imprimir` = '2', `id_remoto` = '7' WHERE `id_remoto` = '7';
UPDATE usuarios SET `nombre_usuario` = 'caja1@carniceria.com.ar', `password` = 'e10adc3949ba59abbe56e057f20f883e', `nombre_completo` = 'Cajero 1', `activo` = '1', `venta_rapida` = '0', `lista_precios` = '1', `imprimir` = '1', `tipo_comprobante_imprimir` = '1', `id_remoto` = '8' WHERE `id_remoto` = '8';
UPDATE usuarios SET `nombre_usuario` = 'suc2@carniceria.com.ar', `password` = 'e10adc3949ba59abbe56e057f20f883e', `nombre_completo` = 'Cajero 1', `activo` = '1', `venta_rapida` = '0', `lista_precios` = '1', `imprimir` = '1', `tipo_comprobante_imprimir` = '1', `id_remoto` = '9' WHERE `id_remoto` = '9';
UPDATE usuarios SET `nombre_usuario` = 'admin2@carniceria.com.ar', `password` = 'e10adc3949ba59abbe56e057f20f883e', `nombre_completo` = 'Cajero 1', `activo` = '1', `venta_rapida` = '0', `lista_precios` = '1', `imprimir` = '1', `tipo_comprobante_imprimir` = '1', `id_remoto` = '10' WHERE `id_remoto` = '10';
UPDATE usuarios SET `nombre_usuario` = 'admin@admin.com.ar', `password` = 'e10adc3949ba59abbe56e057f20f883e', `nombre_completo` = 'Vendedor del Kiosco', `activo` = NULL, `venta_rapida` = '0', `lista_precios` = '1', `imprimir` = '1', `tipo_comprobante_imprimir` = '1', `id_remoto` = '35' WHERE `id_remoto` = '35';
UPDATE tipo_documento SET `nombre` = 'DNI', `id_remoto` = '12' WHERE `id_remoto` = '12';
UPDATE tipo_documento SET `nombre` = 'L.E.', `id_remoto` = '13' WHERE `id_remoto` = '13';
UPDATE tipo_documento SET `nombre` = 'PASAPORTE', `id_remoto` = '14' WHERE `id_remoto` = '14';
UPDATE tipo_iva SET `nombre` = 'INSCRIPTO', `descripcion` = NULL, `porcentaje` = NULL, `letra_factura` = 'A', `id_remoto` = '11' WHERE `id_remoto` = '11';
UPDATE tipo_iva SET `nombre` = 'MONOTRIBUTO', `descripcion` = NULL, `porcentaje` = NULL, `letra_factura` = 'C', `id_remoto` = '12' WHERE `id_remoto` = '12';
UPDATE tipo_iva SET `nombre` = 'CONSUMIDOR FINAL', `descripcion` = NULL, `porcentaje` = NULL, `letra_factura` = 'B', `id_remoto` = '13' WHERE `id_remoto` = '13';
UPDATE tipo_iva SET `nombre` = 'INSCRIPTO EXENTO', `descripcion` = NULL, `porcentaje` = NULL, `letra_factura` = NULL, `id_remoto` = '36' WHERE `id_remoto` = '36';
UPDATE vendedores SET `nombre` = 'CAJERO 1', `direccion` = NULL, `telefono` = NULL, `porcentaje_comision` = NULL, `id_remoto` = '26' WHERE `id_remoto` = '26';
UPDATE vendedores SET `nombre` = 'CAJERO 2', `direccion` = NULL, `telefono` = NULL, `porcentaje_comision` = NULL, `id_remoto` = '27' WHERE `id_remoto` = '27';
UPDATE vendedores SET `nombre` = 'CAJERO 3', `direccion` = NULL, `telefono` = NULL, `porcentaje_comision` = NULL, `id_remoto` = '28' WHERE `id_remoto` = '28';
UPDATE codigos_barras SET `inicio` = '2', `id_long` = '5', `payload_type` = 'P', `payload_int` = '5', `long` = '13', `id_remoto` = '1' WHERE `id_remoto` = '1';
UPDATE tasa_iva SET `nombre` = '21%', `tasa` = '0.21', `id_remoto` = '4' WHERE `id_remoto` = '4';
UPDATE tasa_iva SET `nombre` = '10,5%', `tasa` = '0.105', `id_remoto` = '5' WHERE `id_remoto` = '5';
UPDATE tasa_iva SET `nombre` = '0%', `tasa` = '0', `id_remoto` = '6' WHERE `id_remoto` = '6';
UPDATE familias SET `numero` = '1', `nombre` = 'CERDO', `id_remoto` = '11' WHERE `id_remoto` = '11';
UPDATE familias SET `numero` = '2', `nombre` = 'POLLO', `id_remoto` = '12' WHERE `id_remoto` = '12';
UPDATE familias SET `numero` = '3', `nombre` = 'LECHÓN', `id_remoto` = '13' WHERE `id_remoto` = '13';
UPDATE familias SET `numero` = '4', `nombre` = 'CORDERO', `id_remoto` = '14' WHERE `id_remoto` = '14';
UPDATE familias SET `numero` = '5', `nombre` = 'TERNERA', `id_remoto` = '15' WHERE `id_remoto` = '15';
UPDATE familias SET `numero` = '6', `nombre` = 'TERNERA POR PIEZA', `id_remoto` = '16' WHERE `id_remoto` = '16';
UPDATE familias SET `numero` = '7', `nombre` = 'PRODUCCIÓN', `id_remoto` = '17' WHERE `id_remoto` = '17';
UPDATE familias SET `numero` = '8', `nombre` = 'VARIOS', `id_remoto` = '18' WHERE `id_remoto` = '18';
UPDATE familias SET `numero` = '9', `nombre` = 'ACHURA', `id_remoto` = '19' WHERE `id_remoto` = '19';
UPDATE familias SET `numero` = '10', `nombre` = 'CONGELADOS', `id_remoto` = '20' WHERE `id_remoto` = '20';
UPDATE proveedores SET `razon_social` = 'Proveedor por defecto', `direccion` = '111111', `telefono` = '111111', `email` = 'info@proveedor_prueba.com.ar', `cuit` = '1111', `saldo_actual` = '0', `id_remoto` = '27' WHERE `id_remoto` = '27';
UPDATE proveedores SET `razon_social` = 'Prueba', `direccion` = '1', `telefono` = '12345', `email` = 'prueba@n.com', `cuit` = '1111111111', `saldo_actual` = '0', `id_remoto` = '51' WHERE `id_remoto` = '51';
UPDATE tipo SET `numero` = '1', `nombre` = 'Producto', `id_remoto` = '8' WHERE `id_remoto` = '8';
UPDATE tipo SET `numero` = '2', `nombre` = 'Servicio', `id_remoto` = '9' WHERE `id_remoto` = '9';
UPDATE tipo SET `numero` = '3', `nombre` = 'Favorito', `id_remoto` = '10' WHERE `id_remoto` = '10';
UPDATE unidad SET `nombre` = 'KILOGRAMO', `simbolo` = 'KG', `id_remoto` = '19' WHERE `id_remoto` = '19';
UPDATE unidad SET `nombre` = 'UNIDAD', `simbolo` = 'UNIDAD', `id_remoto` = '20' WHERE `id_remoto` = '20';
UPDATE unidad SET `nombre` = 'CAJA', `simbolo` = 'CAJA', `id_remoto` = '21' WHERE `id_remoto` = '21';
UPDATE unidad SET `nombre` = 'METRO', `simbolo` = 'METRO', `id_remoto` = '22' WHERE `id_remoto` = '22';
UPDATE unidad SET `nombre` = 'HORA', `simbolo` = 'Hs.', `id_remoto` = '80' WHERE `id_remoto` = '80';
UPDATE unidad SET `nombre` = 'DOCENA', `simbolo` = 'DOC.', `id_remoto` = '116' WHERE `id_remoto` = '116';
UPDATE unidad SET `nombre` = 'DOCENA', `simbolo` = 'DOC.', `id_remoto` = '117' WHERE `id_remoto` = '117';
UPDATE unidad SET `nombre` = 'DOCENA', `simbolo` = 'DOC.', `id_remoto` = '118' WHERE `id_remoto` = '118';
UPDATE forma_pago SET `nombre` = 'EFECTIVO', `porcentaje` = '0', `activo` = '1', `id_remoto` = '13' WHERE `id_remoto` = '13';
UPDATE forma_pago SET `nombre` = '3 CUOTAS', `porcentaje` = '15', `activo` = '1', `id_remoto` = '14' WHERE `id_remoto` = '14';
UPDATE forma_pago SET `nombre` = '6 CUOTAS', `porcentaje` = '60', `activo` = '1', `id_remoto` = '15' WHERE `id_remoto` = '15';
UPDATE funciones SET `nombre` = 'productos', `descripcion` = 'Productos', `id_remoto` = '52' WHERE `id_remoto` = '52';
UPDATE funciones SET `nombre` = 'comprobantes', `descripcion` = 'Comprobantes', `id_remoto` = '53' WHERE `id_remoto` = '53';
UPDATE funciones SET `nombre` = 'clientes', `descripcion` = 'Clientes', `id_remoto` = '54' WHERE `id_remoto` = '54';
UPDATE funciones SET `nombre` = 'agrupaciones', `descripcion` = 'Agrupaciones', `id_remoto` = '55' WHERE `id_remoto` = '55';
UPDATE funciones SET `nombre` = 'categorias', `descripcion` = 'Categorias', `id_remoto` = '56' WHERE `id_remoto` = '56';
UPDATE funciones SET `nombre` = 'categoria_iibb', `descripcion` = 'Categoria IIBB', `id_remoto` = '57' WHERE `id_remoto` = '57';
UPDATE funciones SET `nombre` = 'cierre_cajas', `descripcion` = 'Cierres Cajas', `id_remoto` = '58' WHERE `id_remoto` = '58';
UPDATE funciones SET `nombre` = 'condiciones_venta', `descripcion` = 'Condiciones Venta', `id_remoto` = '59' WHERE `id_remoto` = '59';
UPDATE funciones SET `nombre` = 'configuraciones', `descripcion` = 'Configuraciones', `id_remoto` = '60' WHERE `id_remoto` = '60';
UPDATE funciones SET `nombre` = 'familias', `descripcion` = 'Familias', `id_remoto` = '61' WHERE `id_remoto` = '61';
UPDATE funciones SET `nombre` = 'formas_pago', `descripcion` = 'Formas de pago', `id_remoto` = '62' WHERE `id_remoto` = '62';
UPDATE funciones SET `nombre` = 'ganancias_clientes', `descripcion` = 'Ganancias de clientes', `id_remoto` = '63' WHERE `id_remoto` = '63';
UPDATE funciones SET `nombre` = 'ganancias_prooveedor', `descripcion` = 'Ganancias prooveedor', `id_remoto` = '64' WHERE `id_remoto` = '64';
UPDATE funciones SET `nombre` = 'listas_pecios', `descripcion` = 'Listas de pecios', `id_remoto` = '65' WHERE `id_remoto` = '65';
UPDATE funciones SET `nombre` = 'localidades', `descripcion` = 'Localidades', `id_remoto` = '66' WHERE `id_remoto` = '66';
UPDATE funciones SET `nombre` = 'marcas', `descripcion` = 'Marcas', `id_remoto` = '67' WHERE `id_remoto` = '67';
UPDATE funciones SET `nombre` = 'monedas', `descripcion` = 'Monedas', `id_remoto` = '68' WHERE `id_remoto` = '68';
UPDATE funciones SET `nombre` = 'operacion_negocio', `descripcion` = 'Operacion Negocio', `id_remoto` = '69' WHERE `id_remoto` = '69';
UPDATE funciones SET `nombre` = 'pais', `descripcion` = 'Pais', `id_remoto` = '70' WHERE `id_remoto` = '70';
UPDATE funciones SET `nombre` = 'presupuestos', `descripcion` = 'presupuestos', `id_remoto` = '71' WHERE `id_remoto` = '71';
UPDATE funciones SET `nombre` = 'productos_stock', `descripcion` = 'Productos Stock', `id_remoto` = '72' WHERE `id_remoto` = '72';
UPDATE funciones SET `nombre` = 'promociones', `descripcion` = 'Promociones', `id_remoto` = '73' WHERE `id_remoto` = '73';
UPDATE funciones SET `nombre` = 'proveedores', `descripcion` = 'proveedores', `id_remoto` = '74' WHERE `id_remoto` = '74';
UPDATE funciones SET `nombre` = 'proveedores', `descripcion` = 'Proveedores', `id_remoto` = '75' WHERE `id_remoto` = '75';
UPDATE funciones SET `nombre` = 'provincia_categoria_iibb', `descripcion` = 'Provincia Categoria IIBB', `id_remoto` = '76' WHERE `id_remoto` = '76';
UPDATE funciones SET `nombre` = 'provincia_iva_proveedor', `descripcion` = 'Provincia IVA proveedor', `id_remoto` = '77' WHERE `id_remoto` = '77';
UPDATE funciones SET `nombre` = 'provincias', `descripcion` = 'provincias', `id_remoto` = '78' WHERE `id_remoto` = '78';
UPDATE funciones SET `nombre` = 'remitos', `descripcion` = 'remitos', `id_remoto` = '79' WHERE `id_remoto` = '79';
UPDATE funciones SET `nombre` = 'roles', `descripcion` = 'Roles', `id_remoto` = '80' WHERE `id_remoto` = '80';
UPDATE funciones SET `nombre` = 'subcategoria', `descripcion` = 'Sub Categoria', `id_remoto` = '81' WHERE `id_remoto` = '81';
UPDATE funciones SET `nombre` = 'subfamilias', `descripcion` = 'Sub Familias', `id_remoto` = '82' WHERE `id_remoto` = '82';
UPDATE funciones SET `nombre` = 'sucursales', `descripcion` = 'Sucursales', `id_remoto` = '83' WHERE `id_remoto` = '83';
UPDATE funciones SET `nombre` = 'tipo', `descripcion` = 'Tipo', `id_remoto` = '84' WHERE `id_remoto` = '84';
UPDATE funciones SET `nombre` = 'tipo_comprobante', `descripcion` = 'Tipo Comprobante', `id_remoto` = '85' WHERE `id_remoto` = '85';
UPDATE funciones SET `nombre` = 'tipo_documento', `descripcion` = 'Tipo Documento', `id_remoto` = '86' WHERE `id_remoto` = '86';
UPDATE funciones SET `nombre` = 'tipo_iva', `descripcion` = 'Tipo de IVA', `id_remoto` = '87' WHERE `id_remoto` = '87';
UPDATE funciones SET `nombre` = 'tipos_cajas', `descripcion` = 'Tipos Cajas', `id_remoto` = '88' WHERE `id_remoto` = '88';
UPDATE funciones SET `nombre` = 'ubicacion', `descripcion` = 'Ubicacion', `id_remoto` = '89' WHERE `id_remoto` = '89';
UPDATE funciones SET `nombre` = 'unidad', `descripcion` = 'Unidad', `id_remoto` = '90' WHERE `id_remoto` = '90';
UPDATE funciones SET `nombre` = 'usuarios', `descripcion` = 'Usuarios', `id_remoto` = '91' WHERE `id_remoto` = '91';
UPDATE funciones SET `nombre` = 'vendedores', `descripcion` = 'Vendedores', `id_remoto` = '92' WHERE `id_remoto` = '92';
UPDATE funciones SET `nombre` = 'stock', `descripcion` = 'Stock', `id_remoto` = '93' WHERE `id_remoto` = '93';
UPDATE funciones SET `nombre` = 'gastos', `descripcion` = 'Gastos', `id_remoto` = '94' WHERE `id_remoto` = '94';
UPDATE funciones SET `nombre` = 'compras', `descripcion` = 'Compras', `id_remoto` = '95' WHERE `id_remoto` = '95';
UPDATE movimientos_stock SET `cantidad` = '-1', `observaciones` = NULL, `id_remoto` = '1' WHERE `id_remoto` = '1';
UPDATE movimientos_stock SET `cantidad` = '-1', `observaciones` = NULL, `id_remoto` = '2' WHERE `id_remoto` = '2';
UPDATE movimientos_stock SET `cantidad` = '-1', `observaciones` = NULL, `id_remoto` = '3' WHERE `id_remoto` = '3';
UPDATE movimientos_stock SET `cantidad` = '1', `observaciones` = NULL, `id_remoto` = '4' WHERE `id_remoto` = '4';
UPDATE movimientos_stock SET `cantidad` = '1', `observaciones` = NULL, `id_remoto` = '5' WHERE `id_remoto` = '5';
UPDATE movimientos_stock SET `cantidad` = '1', `observaciones` = NULL, `id_remoto` = '6' WHERE `id_remoto` = '6';
UPDATE movimientos_stock SET `cantidad` = '-1', `observaciones` = 'Venta de productos', `id_remoto` = '7' WHERE `id_remoto` = '7';
UPDATE movimientos_stock SET `cantidad` = '-1', `observaciones` = 'Venta de productos', `id_remoto` = '8' WHERE `id_remoto` = '8';
UPDATE movimientos_stock SET `cantidad` = '-1', `observaciones` = 'Venta de productos', `id_remoto` = '9' WHERE `id_remoto` = '9';
UPDATE movimientos_stock SET `cantidad` = '-1', `observaciones` = 'Venta de productos', `id_remoto` = '10' WHERE `id_remoto` = '10';
UPDATE movimientos_stock SET `cantidad` = '-1', `observaciones` = 'Venta de productos', `id_remoto` = '11' WHERE `id_remoto` = '11';
UPDATE movimientos_stock SET `cantidad` = '-1', `observaciones` = 'Venta de productos', `id_remoto` = '12' WHERE `id_remoto` = '12';
UPDATE movimientos_stock SET `cantidad` = '-1', `observaciones` = 'Venta de productos', `id_remoto` = '13' WHERE `id_remoto` = '13';
UPDATE movimientos_stock SET `cantidad` = '-1', `observaciones` = 'Venta de productos', `id_remoto` = '14' WHERE `id_remoto` = '14';
UPDATE movimientos_stock SET `cantidad` = '1', `observaciones` = 'Anulación de factura 84 motivo: ', `id_remoto` = '15' WHERE `id_remoto` = '15';
UPDATE movimientos_stock SET `cantidad` = '1', `observaciones` = 'Anulación de factura 84 motivo: ', `id_remoto` = '16' WHERE `id_remoto` = '16';
UPDATE movimientos_stock SET `cantidad` = '1', `observaciones` = 'Anulación de factura 84 motivo: ', `id_remoto` = '17' WHERE `id_remoto` = '17';
UPDATE movimientos_stock SET `cantidad` = '-1', `observaciones` = 'Venta de productos', `id_remoto` = '18' WHERE `id_remoto` = '18';
UPDATE movimientos_stock SET `cantidad` = '-1', `observaciones` = 'Venta de productos', `id_remoto` = '19' WHERE `id_remoto` = '19';
UPDATE movimientos_stock SET `cantidad` = '-1', `observaciones` = 'Venta de productos', `id_remoto` = '20' WHERE `id_remoto` = '20';
UPDATE movimientos_stock SET `cantidad` = '-1', `observaciones` = 'Venta de productos', `id_remoto` = '21' WHERE `id_remoto` = '21';
UPDATE movimientos_stock SET `cantidad` = '-1', `observaciones` = 'Venta de productos', `id_remoto` = '22' WHERE `id_remoto` = '22';
UPDATE movimientos_stock SET `cantidad` = '-1', `observaciones` = 'Venta de productos', `id_remoto` = '23' WHERE `id_remoto` = '23';
UPDATE movimientos_stock SET `cantidad` = '-1', `observaciones` = 'Venta de productos', `id_remoto` = '24' WHERE `id_remoto` = '24';
UPDATE movimientos_stock SET `cantidad` = '-1', `observaciones` = 'Venta de productos', `id_remoto` = '25' WHERE `id_remoto` = '25';
UPDATE movimientos_stock SET `cantidad` = '-1', `observaciones` = 'Venta de productos', `id_remoto` = '26' WHERE `id_remoto` = '26';
UPDATE movimientos_stock SET `cantidad` = '-1', `observaciones` = 'Venta de productos', `id_remoto` = '27' WHERE `id_remoto` = '27';
UPDATE movimientos_stock SET `cantidad` = '1', `observaciones` = 'Anulación de factura 88 motivo: Bifes', `id_remoto` = '28' WHERE `id_remoto` = '28';
UPDATE movimientos_stock SET `cantidad` = '1', `observaciones` = 'Anulación de factura 88 motivo: Bifes', `id_remoto` = '29' WHERE `id_remoto` = '29';
UPDATE movimientos_stock SET `cantidad` = '1', `observaciones` = 'Anulación de factura 88 motivo: Bifes', `id_remoto` = '30' WHERE `id_remoto` = '30';
UPDATE movimientos_stock SET `cantidad` = '1', `observaciones` = 'Anulación de factura 88 motivo: Bifes', `id_remoto` = '31' WHERE `id_remoto` = '31';
UPDATE movimientos_stock SET `cantidad` = '1', `observaciones` = 'Anulación de factura 88 motivo: Bifes', `id_remoto` = '32' WHERE `id_remoto` = '32';
UPDATE movimientos_stock SET `cantidad` = '1', `observaciones` = 'Anulación de factura 88 motivo: Bifes', `id_remoto` = '33' WHERE `id_remoto` = '33';
UPDATE movimientos_stock SET `cantidad` = '-1', `observaciones` = 'Venta de productos', `id_remoto` = '34' WHERE `id_remoto` = '34';
UPDATE movimientos_stock SET `cantidad` = '-1', `observaciones` = 'Venta de productos', `id_remoto` = '35' WHERE `id_remoto` = '35';
UPDATE movimientos_stock SET `cantidad` = '-1', `observaciones` = 'Venta de productos', `id_remoto` = '36' WHERE `id_remoto` = '36';
UPDATE movimientos_stock SET `cantidad` = '-20', `observaciones` = 'Venta de productos', `id_remoto` = '37' WHERE `id_remoto` = '37';
UPDATE movimientos_stock SET `cantidad` = '20', `observaciones` = 'Anulación de factura 93 motivo: anulacion', `id_remoto` = '38' WHERE `id_remoto` = '38';
UPDATE promociones SET `nombre` = 'PROMO EFECTIVO', `descripcion` = NULL, `porcentaje` = '5', `id_remoto` = '3' WHERE `id_remoto` = '3';
UPDATE pagos SET `nro_factura` = '00002', `monto` = '218600', `nro_comprobante` = NULL, `id_remoto` = '1' WHERE `id_remoto` = '1';
UPDATE pagos SET `nro_factura` = '00003', `monto` = '200000', `nro_comprobante` = '1234', `id_remoto` = '2' WHERE `id_remoto` = '2';
UPDATE pagos SET `nro_factura` = '00003', `monto` = '62000', `nro_comprobante` = '321', `id_remoto` = '3' WHERE `id_remoto` = '3';
UPDATE pagos SET `nro_factura` = '00003', `monto` = '99300', `nro_comprobante` = '21312341', `id_remoto` = '4' WHERE `id_remoto` = '4';
UPDATE pagos SET `nro_factura` = '1', `monto` = '3000', `nro_comprobante` = '654', `id_remoto` = '5' WHERE `id_remoto` = '5';
UPDATE pagos SET `nro_factura` = '1', `monto` = '1000', `nro_comprobante` = '1', `id_remoto` = '6' WHERE `id_remoto` = '6';
UPDATE pagos SET `nro_factura` = '1', `monto` = '690', `nro_comprobante` = NULL, `id_remoto` = '7' WHERE `id_remoto` = '7';
UPDATE pagos SET `nro_factura` = '11111', `monto` = '480', `nro_comprobante` = '1234', `id_remoto` = '8' WHERE `id_remoto` = '8';
SET foreign_key_checks = 1;
