SET foreign_key_checks = 0;
UPDATE moneda SET `simbolo` = '$', `nombre` = 'Pesos argentinos', `cotizacion` = '1', `id_remoto` = '29' WHERE `id_remoto` = '29';
UPDATE moneda SET `simbolo` = 'USD', `nombre` = 'Dólar estadounidense', `cotizacion` = '886', `id_remoto` = '30' WHERE `id_remoto` = '30';
UPDATE agrupacion SET `numero` = '1', `nombre` = 'GENERAL', `color` = '#0098DA', `icono` = 'fas fa-boxes', `id_remoto` = '23' WHERE `id_remoto` = '23';
UPDATE categoria SET `nombre` = 'CATEGORIA', `se_imprime` = '1', `id_remoto` = '21' WHERE `id_remoto` = '21';
UPDATE puntos_venta SET `numero` = '3', `descripcion` = 'Punto de venta 3', `id_remoto` = '9' WHERE `id_remoto` = '9';
UPDATE puntos_venta SET `numero` = '4', `descripcion` = 'Punto de venta 4', `id_remoto` = '10' WHERE `id_remoto` = '10';
UPDATE sucursales SET `nombre` = 'Store Centenario', `direccion` = 'Camino Centenario 1232 - 1896 - City Bell - Buenos Aires', `telefono` = '2216948034', `email` = 'storecentenario.sa@gmail.com', `contacto_nombre` = NULL, `contacto_telefono` = NULL, `contacto_email` = NULL, `referente_nombre` = NULL, `referente_telefono` = NULL, `referente_email` = NULL, `id_remoto` = '22' WHERE `id_remoto` = '22';
UPDATE roles SET `nombre` = 'cajero', `descripcion` = 'Cajero/Vendedor', `id_remoto` = '40' WHERE `id_remoto` = '40';
UPDATE roles SET `nombre` = 'admin', `descripcion` = 'Administrador', `id_remoto` = '41' WHERE `id_remoto` = '41';
UPDATE usuarios SET `nombre_usuario` = 'admin@bermudezstore.com', `password` = 'a989ed30b315bc5567cb0f9a1c66758f', `nombre_completo` = 'Administrador', `activo` = '1', `venta_rapida` = '1', `lista_precios` = '1', `imprimir` = '1', `tipo_comprobante_imprimir` = '2', `id_remoto` = '40' WHERE `id_remoto` = '40';
UPDATE usuarios SET `nombre_usuario` = 'puesto1@bermudezstore.com', `password` = '3c27f30203614d29f49ede5ebf5754c6', `nombre_completo` = 'Puesto de venta 1', `activo` = '1', `venta_rapida` = '1', `lista_precios` = '1', `imprimir` = '1', `tipo_comprobante_imprimir` = '2', `id_remoto` = '43' WHERE `id_remoto` = '43';
UPDATE usuarios SET `nombre_usuario` = 'puesto2@bermudezstore.com', `password` = '3c27f30203614d29f49ede5ebf5754c6', `nombre_completo` = 'Puesto de venta 2', `activo` = '1', `venta_rapida` = '1', `lista_precios` = '1', `imprimir` = '1', `tipo_comprobante_imprimir` = '2', `id_remoto` = '44' WHERE `id_remoto` = '44';
UPDATE usuarios SET `nombre_usuario` = 'puesto3@bermudezstore.com', `password` = '3c27f30203614d29f49ede5ebf5754c6', `nombre_completo` = 'Puesto de venta 3', `activo` = '1', `venta_rapida` = '1', `lista_precios` = '1', `imprimir` = '1', `tipo_comprobante_imprimir` = '2', `id_remoto` = '45' WHERE `id_remoto` = '45';
UPDATE tipo_documento SET `nombre` = 'DNI', `id_remoto` = '18' WHERE `id_remoto` = '18';
UPDATE tipo_documento SET `nombre` = 'L.E.', `id_remoto` = '19' WHERE `id_remoto` = '19';
UPDATE tipo_documento SET `nombre` = 'PASAPORTE', `id_remoto` = '20' WHERE `id_remoto` = '20';
UPDATE tipo_iva SET `nombre` = 'INSCRIPTO', `descripcion` = NULL, `porcentaje` = NULL, `letra_factura` = 'A', `id_remoto` = '17' WHERE `id_remoto` = '17';
UPDATE tipo_iva SET `nombre` = 'MONOTRIBUTO', `descripcion` = NULL, `porcentaje` = NULL, `letra_factura` = 'C', `id_remoto` = '18' WHERE `id_remoto` = '18';
UPDATE tipo_iva SET `nombre` = 'CONSUMIDOR FINAL', `descripcion` = NULL, `porcentaje` = NULL, `letra_factura` = 'B', `id_remoto` = '19' WHERE `id_remoto` = '19';
UPDATE vendedores SET `nombre` = 'VENDEROR', `direccion` = NULL, `telefono` = NULL, `porcentaje_comision` = '0', `id_remoto` = '39' WHERE `id_remoto` = '39';
UPDATE codigos_barras SET `inicio` = '2', `id_long` = '5', `payload_type` = 'P', `payload_int` = '5', `long` = '13', `id_remoto` = '13' WHERE `id_remoto` = '13';
UPDATE tasa_iva SET `nombre` = 'IVA 21%', `tasa` = '0.21', `id_remoto` = '40' WHERE `id_remoto` = '40';
UPDATE tasa_iva SET `nombre` = 'IVA 10.5%', `tasa` = '0.105', `id_remoto` = '41' WHERE `id_remoto` = '41';
UPDATE tasa_iva SET `nombre` = 'Sin IVA', `tasa` = '0', `id_remoto` = '42' WHERE `id_remoto` = '42';
UPDATE familias SET `numero` = '1', `nombre` = 'GENERAL', `id_remoto` = '32' WHERE `id_remoto` = '32';
UPDATE proveedores SET `razon_social` = 'Proveedor por defecto', `direccion` = 'Calle Ejemplo 123', `telefono` = '12345678', `email` = 'proveedor@example.com', `cuit` = '11111111', `saldo_actual` = '0', `id_remoto` = '40' WHERE `id_remoto` = '40';
UPDATE proveedores SET `razon_social` = 'El rapido srl', `direccion` = '1', `telefono` = '1', `email` = '1', `cuit` = '30717435237', `saldo_actual` = '0', `id_remoto` = '42' WHERE `id_remoto` = '42';
UPDATE proveedores SET `razon_social` = 'SAN JUAN Y SOLIS S.A', `direccion` = 'AV.JUAN B.JUSTO 9165', `telefono` = '08102207597', `email` = 'VENTAS@SANJUANYSOLIS.COM', `cuit` = '30699654309', `saldo_actual` = '0', `id_remoto` = '52' WHERE `id_remoto` = '52';
UPDATE proveedores SET `razon_social` = 'NEUMEN', `direccion` = '1', `telefono` = '1', `email` = '1', `cuit` = '3064007937.8', `saldo_actual` = '0', `id_remoto` = '56' WHERE `id_remoto` = '56';
UPDATE tipo SET `numero` = '1', `nombre` = 'Producto', `id_remoto` = '44' WHERE `id_remoto` = '44';
UPDATE tipo SET `numero` = '2', `nombre` = 'Servicio', `id_remoto` = '45' WHERE `id_remoto` = '45';
UPDATE tipo SET `numero` = '3', `nombre` = 'Producto y servicio', `id_remoto` = '46' WHERE `id_remoto` = '46';
UPDATE unidad SET `nombre` = 'Kilogramo', `simbolo` = 'KG', `id_remoto` = '95' WHERE `id_remoto` = '95';
UPDATE unidad SET `nombre` = 'Unidad', `simbolo` = 'UN.', `id_remoto` = '96' WHERE `id_remoto` = '96';
UPDATE unidad SET `nombre` = 'Metro', `simbolo` = 'M', `id_remoto` = '97' WHERE `id_remoto` = '97';
UPDATE unidad SET `nombre` = 'Metro Cuadrado', `simbolo` = 'M2', `id_remoto` = '98' WHERE `id_remoto` = '98';
UPDATE unidad SET `nombre` = 'Metro Cubico', `simbolo` = 'M3', `id_remoto` = '99' WHERE `id_remoto` = '99';
UPDATE unidad SET `nombre` = 'Litro', `simbolo` = 'LTS.', `id_remoto` = '100' WHERE `id_remoto` = '100';
UPDATE unidad SET `nombre` = 'Gramo', `simbolo` = 'GR.', `id_remoto` = '101' WHERE `id_remoto` = '101';
UPDATE forma_pago SET `nombre` = 'EFECTIVO', `porcentaje` = '0', `activo` = '1', `id_remoto` = '26' WHERE `id_remoto` = '26';
UPDATE forma_pago SET `nombre` = 'TARJETA ', `porcentaje` = '0', `activo` = '1', `id_remoto` = '28' WHERE `id_remoto` = '28';
UPDATE funciones SET `nombre` = 'comprobantes', `descripcion` = 'Comprobantes', `id_remoto` = '675' WHERE `id_remoto` = '675';
UPDATE funciones SET `nombre` = 'productos', `descripcion` = 'Productos', `id_remoto` = '676' WHERE `id_remoto` = '676';
UPDATE funciones SET `nombre` = 'clientes', `descripcion` = 'Clientes', `id_remoto` = '677' WHERE `id_remoto` = '677';
UPDATE funciones SET `nombre` = 'agrupaciones', `descripcion` = 'Agrupaciones', `id_remoto` = '678' WHERE `id_remoto` = '678';
UPDATE funciones SET `nombre` = 'categorias', `descripcion` = 'Categorias', `id_remoto` = '679' WHERE `id_remoto` = '679';
UPDATE funciones SET `nombre` = 'categoria_iibb', `descripcion` = 'Categoria IIBB', `id_remoto` = '680' WHERE `id_remoto` = '680';
UPDATE funciones SET `nombre` = 'cierre_cajas', `descripcion` = 'Cierres Cajas', `id_remoto` = '681' WHERE `id_remoto` = '681';
UPDATE funciones SET `nombre` = 'condiciones_venta', `descripcion` = 'Condiciones Venta', `id_remoto` = '682' WHERE `id_remoto` = '682';
UPDATE funciones SET `nombre` = 'configuraciones', `descripcion` = 'Configuraciones', `id_remoto` = '683' WHERE `id_remoto` = '683';
UPDATE funciones SET `nombre` = 'familias', `descripcion` = 'Familias', `id_remoto` = '684' WHERE `id_remoto` = '684';
UPDATE funciones SET `nombre` = 'formas_pago', `descripcion` = 'Formas de pago', `id_remoto` = '685' WHERE `id_remoto` = '685';
UPDATE funciones SET `nombre` = 'ganancias_clientes', `descripcion` = 'Ganancias de clientes', `id_remoto` = '686' WHERE `id_remoto` = '686';
UPDATE funciones SET `nombre` = 'ganancias_prooveedor', `descripcion` = 'Ganancias prooveedor', `id_remoto` = '687' WHERE `id_remoto` = '687';
UPDATE funciones SET `nombre` = 'listas_pecios', `descripcion` = 'Listas de pecios', `id_remoto` = '688' WHERE `id_remoto` = '688';
UPDATE funciones SET `nombre` = 'localidades', `descripcion` = 'Localidades', `id_remoto` = '689' WHERE `id_remoto` = '689';
UPDATE funciones SET `nombre` = 'marcas', `descripcion` = 'Marcas', `id_remoto` = '690' WHERE `id_remoto` = '690';
UPDATE funciones SET `nombre` = 'monedas', `descripcion` = 'Monedas', `id_remoto` = '691' WHERE `id_remoto` = '691';
UPDATE funciones SET `nombre` = 'operacion_negocio', `descripcion` = 'Operacion Negocio', `id_remoto` = '692' WHERE `id_remoto` = '692';
UPDATE funciones SET `nombre` = 'pais', `descripcion` = 'Pais', `id_remoto` = '693' WHERE `id_remoto` = '693';
UPDATE funciones SET `nombre` = 'presupuestos', `descripcion` = 'presupuestos', `id_remoto` = '694' WHERE `id_remoto` = '694';
UPDATE funciones SET `nombre` = 'productos_stock', `descripcion` = 'Productos Stock', `id_remoto` = '695' WHERE `id_remoto` = '695';
UPDATE funciones SET `nombre` = 'promociones', `descripcion` = 'Promociones', `id_remoto` = '696' WHERE `id_remoto` = '696';
UPDATE funciones SET `nombre` = 'proveedores', `descripcion` = 'proveedores', `id_remoto` = '697' WHERE `id_remoto` = '697';
UPDATE funciones SET `nombre` = 'proveedores', `descripcion` = 'Proveedores', `id_remoto` = '698' WHERE `id_remoto` = '698';
UPDATE funciones SET `nombre` = 'provincia_categoria_iibb', `descripcion` = 'Provincia Categoria IIBB', `id_remoto` = '699' WHERE `id_remoto` = '699';
UPDATE funciones SET `nombre` = 'provincia_iva_proveedor', `descripcion` = 'Provincia IVA proveedor', `id_remoto` = '700' WHERE `id_remoto` = '700';
UPDATE funciones SET `nombre` = 'provincias', `descripcion` = 'provincias', `id_remoto` = '701' WHERE `id_remoto` = '701';
UPDATE funciones SET `nombre` = 'remitos', `descripcion` = 'remitos', `id_remoto` = '702' WHERE `id_remoto` = '702';
UPDATE funciones SET `nombre` = 'roles', `descripcion` = 'Roles', `id_remoto` = '703' WHERE `id_remoto` = '703';
UPDATE funciones SET `nombre` = 'subcategoria', `descripcion` = 'Sub Categoria', `id_remoto` = '704' WHERE `id_remoto` = '704';
UPDATE funciones SET `nombre` = 'subfamilias', `descripcion` = 'Sub Familias', `id_remoto` = '705' WHERE `id_remoto` = '705';
UPDATE funciones SET `nombre` = 'sucursales', `descripcion` = 'Sucursales', `id_remoto` = '706' WHERE `id_remoto` = '706';
UPDATE funciones SET `nombre` = 'tipo', `descripcion` = 'Tipo', `id_remoto` = '707' WHERE `id_remoto` = '707';
UPDATE funciones SET `nombre` = 'tipo_comprobante', `descripcion` = 'Tipo Comprobante', `id_remoto` = '708' WHERE `id_remoto` = '708';
UPDATE funciones SET `nombre` = 'tipo_documento', `descripcion` = 'Tipo Documento', `id_remoto` = '709' WHERE `id_remoto` = '709';
UPDATE funciones SET `nombre` = 'tipo_iva', `descripcion` = 'Tipo de IVA', `id_remoto` = '710' WHERE `id_remoto` = '710';
UPDATE funciones SET `nombre` = 'tipos_cajas', `descripcion` = 'Tipos Cajas', `id_remoto` = '711' WHERE `id_remoto` = '711';
UPDATE funciones SET `nombre` = 'ubicacion', `descripcion` = 'Ubicacion', `id_remoto` = '712' WHERE `id_remoto` = '712';
UPDATE funciones SET `nombre` = 'unidad', `descripcion` = 'Unidad', `id_remoto` = '713' WHERE `id_remoto` = '713';
UPDATE funciones SET `nombre` = 'usuarios', `descripcion` = 'Usuarios', `id_remoto` = '714' WHERE `id_remoto` = '714';
UPDATE funciones SET `nombre` = 'vendedores', `descripcion` = 'Vendedores', `id_remoto` = '715' WHERE `id_remoto` = '715';
UPDATE funciones SET `nombre` = 'stock', `descripcion` = 'Stock', `id_remoto` = '716' WHERE `id_remoto` = '716';
UPDATE funciones SET `nombre` = 'gastos', `descripcion` = 'Gastos', `id_remoto` = '717' WHERE `id_remoto` = '717';
UPDATE funciones SET `nombre` = 'compras', `descripcion` = 'Compras', `id_remoto` = '718' WHERE `id_remoto` = '718';
SET foreign_key_checks = 1;
