UPDATE moneda SET `simbolo` = 'USD', `nombre` = 'Dólar estadounidense', `cotizacion` = '1042', `id_remoto` = '7' WHERE `id_remoto` = '7';
UPDATE agrupacion SET `numero` = '1', `nombre` = 'CARNICERIA', `color` = '#0098DA', `icono` = 'fas fa-boxes', `id_remoto` = '10' WHERE `id_remoto` = '10';
UPDATE categoria SET `nombre` = 'CATEGORIA', `se_imprime` = '1', `id_remoto` = '18' WHERE `id_remoto` = '18';
UPDATE puntos_venta SET `numero` = '1', `descripcion` = 'Punto de venta 1', `id_remoto` = '2' WHERE `id_remoto` = '2';
UPDATE sucursales SET `nombre` = 'Sucursal 1', `direccion` = ' 955, Av.123, B1900 Tolosa, Provincia de Buenos Aires', `telefono` = '2214865781', `email` = 'sucursal7@carnesleo.com.ar', `contacto_nombre` = NULL, `contacto_telefono` = NULL, `contacto_email` = NULL, `referente_nombre` = NULL, `referente_telefono` = NULL, `referente_email` = NULL, `id_remoto` = '1' WHERE `id_remoto` = '1';
UPDATE roles SET `nombre` = 'admin', `descripcion` = 'Administrador', `id_remoto` = '5' WHERE `id_remoto` = '5';
UPDATE usuarios SET `nombre_usuario` = 'admin@carniceria.com.ar', `password` = 'e10adc3949ba59abbe56e057f20f883e', `nombre_completo` = 'Administrador', `activo` = '1', `venta_rapida` = '1', `lista_precios` = '1', `imprimir` = '1', `tipo_comprobante_imprimir` = '2', `id_remoto` = '7' WHERE `id_remoto` = '7';
UPDATE tipo_documento SET `nombre` = 'DNI', `id_remoto` = '12' WHERE `id_remoto` = '12';
UPDATE tipo_iva SET `nombre` = 'INSCRIPTO', `descripcion` = '', `porcentaje` = '', `letra_factura` = 'A', `id_remoto` = '11' WHERE `id_remoto` = '11';
UPDATE vendedores SET `nombre` = 'CAJERO 1', `direccion` = '', `telefono` = '', `porcentaje_comision` = '', `fecha_ingreso` = '2024-04-09', `id_remoto` = '26' WHERE `id_remoto` = '26';
UPDATE clientes SET `nro_cliente` = '13', `nombre` = 'LOPEZ OSORNIO MATIAS', `cuit` = '20321089675', `numero_documento` = '32108967', `direccion_comercial` = '522 e 9 y 10 1436', `direccion_entrega` = NULL, `telefono` = NULL, `celular` = NULL, `email` = NULL, `contacto` = NULL, `telefono_contacto` = NULL, `porcentaje_descuento` = '0', `limite_credito` = '0', `saldo_inicial` = '0', `saldo_actual` = '-3000', `fecha_ultima_compra` = '', `fecha_ultimo_pago` = '', `percepcion_iibb` = '0', `desactivado` = '', `id_remoto` = '35' WHERE `id_remoto` = '35';
UPDATE codigos_barras SET `inicio` = '2', `id_long` = '5', `payload_type` = 'P', `payload_int` = '5', `long` = '13', `id_remoto` = '1' WHERE `id_remoto` = '1';
UPDATE tasa_iva SET `nombre` = '21%', `tasa` = '0.21', `id_remoto` = '4' WHERE `id_remoto` = '4';
UPDATE familias SET `numero` = '1', `nombre` = 'CERDO', `id_remoto` = '11' WHERE `id_remoto` = '11';
UPDATE proveedores SET `razon_social` = 'Proveedor por defecto', `direccion` = '111111', `telefono` = '111111', `email` = 'info@proveedor_prueba.com.ar', `cuit` = '1111', `fecha_ultima_compra` = '', `fecha_ultimo_pago` = '', `saldo_actual` = '0', `id_remoto` = '27' WHERE `id_remoto` = '27';
UPDATE tipo SET `numero` = '1', `nombre` = 'Producto', `id_remoto` = '8' WHERE `id_remoto` = '8';
UPDATE unidad SET `nombre` = 'KILOGRAMO', `simbolo` = 'KG', `id_remoto` = '19' WHERE `id_remoto` = '19';
UPDATE productos SET `codigo` = '1', `descripcion` = 'Americano de cerdo', `descripcion_ampliada` = '', `codigo_barra` = '1', `fecha_alta` = '2024-04-09', `fecha_actualizacion` = '2024-08-27 17:37:13', `articulo_activado` = '', `producto_balanza` = '1', `precio_costo` = '1495', `tasa_iva` = '4', `incluye_iva` = '1', `impuesto_interno` = '0', `precio1` = '3990', `precio2` = '40000', `precio3` = '0', `fraccionado` = '0', `rg5329_23` = '0', `activo` = '0', `texto_panel` = NULL, `stock` = '19', `stock_minimo` = '0', `stock_pedido` = '', `iibb` = '0', `codigo_barra2` = NULL, `oferta` = '0', `margen_ganancia` = '166.89', `publicado_web` = '0', `favorito` = '0', `tipo_impuesto_interno` = '1', `id_remoto` = '645' WHERE `id_remoto` = '645';
UPDATE forma_pago SET `nombre` = 'EFECTIVO', `porcentaje` = '0', `activo` = '1', `id_remoto` = '13' WHERE `id_remoto` = '13';
UPDATE funciones SET `nombre` = 'productos', `descripcion` = 'Productos', `id_remoto` = '52' WHERE `id_remoto` = '52';
UPDATE funciones_roles SET `permite_crear` = '1', `permite_ver` = '1', `permite_modificar` = '1', `permite_eliminar` = '1', `permite_imprimir` = '1', `permite_listar` = '1' WHERE `id_remoto` = '';
UPDATE movimientos_stock SET `cantidad` = '-1', `observaciones` = '', `fecha` = '2024-04-29 21:00:49.025455', `id_remoto` = '1' WHERE `id_remoto` = '1';
UPDATE promociones SET `nombre` = 'PROMO EFECTIVO', `descripcion` = '', `porcentaje` = '5', `id_remoto` = '3' WHERE `id_remoto` = '3';
UPDATE pagos SET `nro_factura` = '00002', `monto` = '218600', `fecha` = '2024-06-18', `nro_comprobante` = '', `id_remoto` = '1' WHERE `id_remoto` = '1';
